### ISSUE TITLE
About the android project

### ISSUE THREAD

**Issue by RobinHan24** [anilsathyan7/Portrait-Segmentation#5]
Could you please provide the android project, thanks a lot.

**Comment by boehm-e** [comment]
Yes it would be really nice :)

**Comment by anilsathyan7** [comment]
Actually i need to clean up the messy android code and i'am planning to include some additional optimizations. I'am also waiting for some other related github issues to be resolved in this regard.
Once it's done i will upload the android project as well.

Also, checkout the other links  to android projects, for segmentation.

**Comment by boehm-e** [comment]
Ok, thank you :)
I checked all the  android segmentation links i could find, but they are running with to much latency for my purpose.
What i am looking is more body segmentation than just portrait, but i look forward to test your implementation ! 
Thank you for your work :1st_place_medal:

**Comment by anilsathyan7** [comment]
@boehm-e  i was actually working on the same stuff. Which data-set did you use? Supervisely?
The problem i feel is that if you want to capture more complexity, say full body instead of simple portrait, you need a model with larger input size or more number of layers. Again there will be a trade-off between accuracy and latency. For full body, 128 input size is way too small; but i think 224 will be sufficient.Finally make sure you have a sufficiently large and good dataset that fully represents your use case or needs. Off-course, it would be very challenging job to get a fully generalized model with very high accuracy and low latency.I think it would be better idea to try a larger/complex(mobile friendly) model first and achieve desired accuracy.Afterwards, you can do all the engineering stuff for optimizations.
Did you try deeplab?

**Comment by boehm-e** [comment]
@anilsathyan7 
I am absolutly not a machine learning expert, so I just tried things other people have done.
I tried deeplab implementation on android device https://github.com/tantara/JejuNet and https://github.com/joaquim-verges/DeeplabAndroid ([demo](https://www.youtube.com/watch?v=zirD2dTxAjU))

The second project runs at about 2-3 fps on my honor 10.
But it classifies all of deeplab classes, and as many people, i just would like to segment people (at higher speed like >15 fps)
Do you know if it is possible to achieve that on android ? Thank you :)

**Comment by anilsathyan7** [comment]
In the demo video that i've shown, the model actually runs at 10-15 fps in my oneplus3. You should get almost the same speed(may be better since you have a better GPU..) using the same model. In fact we tried them on Honor Play, which has almost the same spec's as Honor 10.
If you have a better phone with chips like Sanpdragon 855+Adreno 640 or Kirin+Mali-G76 you can easily get 20 fps.[Still they can't beat apple's iphone ...😜]

I shall upload the app soon ...

**Comment by boehm-e** [comment]
Ok, and in iOS it is human segmentation, do you think it is because their model is well optimized, or it comes from computing power?

**Comment by anilsathyan7** [comment]
According to the [official paper](https://arxiv.org/pdf/1907.01989.pdf), 
"In iOS devices, we benefit from larger cache sizes that result in reduced memory I/O latency, and hence,better performance than the OpenGL backend".
![tflite_speed](https://user-images.githubusercontent.com/1130185/69826286-88c06480-1238-11ea-8120-0b486441e9cb.png)

**Comment by boehm-e** [comment]
@anilsathyan7 Thank you for releasing the app :) 
Will try it as soon as possible :100:

**Comment by boehm-e** [comment]
It works pretty well :) 
I have 10-12 FPS on my Honor 10 (RIP my pocophone f1)
Can I know what is the "munet_mnv3_wm10.tflite" file ?
Thanks

**Comment by anilsathyan7** [comment]
I tried new mobilenetv3 architecture instead of mobilenetv2 with a higher input size i.e 224...It's faster than  corresponfing v2 version; but slightly less accurate. Again to make it even lighter i reduced number of filters and trained on slightly different dataset. But in the end it's test accuracy decreased ...

**Comment by Tomyxtrejo** [comment]
It is possible to have a pre-build apk to test performance? Project looks really good, I get interested in this when I see the TikTok real time segmentation... wow, that impressive

**Comment by anilsathyan7** [comment]
@Tomyxtrejo You can use the **tflite benchmark tool** to benchmark the performance i.e speed of the model(alone) on android.Also you can create apk once you open the project with android studio(Build APK).Performance depends on your hardware and latest tflite gpu delegate (tensorflow); besides my current (unoptimized) code.If you a referring to real-world accuracy (or visual appeal), there seems to a lot of scope for improvement in this regard.I'am still trying to improve performance in this regard !!!

**Comment by Tomyxtrejo** [comment]
@anilsathyan7 Ok I tryed, but the apk give me an error, I will try again. I don`t have Android Studio and I saw that wasn't that easy for a newby to setup the project, but will give a try.

Yes! the green screen filter in tiktok... For a instance i think that was some kind of  processed in the cloud and displayed in my low gamma device (samsung j2 prime) but then I activate airplane mode and still working the same... Is incredible how can go to 15-20 fps at least and have a transparency edges that make it look more soft.
And I found 0 info about that filter online.
